-- H2 2.1.214; 
SET DB_CLOSE_DELAY -1;         
;              
CREATE USER IF NOT EXISTS "SA" SALT '5e0e6713f3066546' HASH '92ee44101db64e33a04f064684dbc4cc01c735f1324bb65769ce83b619f75747' ADMIN;          
CREATE MEMORY TABLE "PUBLIC"."REQUESTFORM"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 3) NOT NULL,
    "CREATED_AT" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "TERMS_AGREED" BOOLEAN NOT NULL,
    "USER_ID" BIGINT NOT NULL
);               
ALTER TABLE "PUBLIC"."REQUESTFORM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("ID");   
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.REQUESTFORM;              
INSERT INTO "PUBLIC"."REQUESTFORM" VALUES
(1, TIMESTAMP WITH TIME ZONE '2023-11-26 22:12:38.456629+00', TRUE, 1),
(2, TIMESTAMP WITH TIME ZONE '2023-11-26 22:13:44.50422+00', TRUE, 3);       
CREATE MEMORY TABLE "PUBLIC"."REQUESTFORM_SECTOR"(
    "REQUESTFORM_ID" BIGINT NOT NULL,
    "SECTOR_ID" BIGINT NOT NULL
);    
ALTER TABLE "PUBLIC"."REQUESTFORM_SECTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("REQUESTFORM_ID", "SECTOR_ID");   
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.REQUESTFORM_SECTOR;      
INSERT INTO "PUBLIC"."REQUESTFORM_SECTOR" VALUES
(1, 43),
(1, 49),
(1, 57),
(1, 59),
(1, 60),
(1, 58),
(2, 21),
(2, 16),
(2, 12),
(2, 17);     
CREATE MEMORY TABLE "PUBLIC"."SECTORS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 80) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PARENT_ID" BIGINT
);         
ALTER TABLE "PUBLIC"."SECTORS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A0" PRIMARY KEY("ID");      
-- 79 +/- SELECT COUNT(*) FROM PUBLIC.SECTORS; 
INSERT INTO "PUBLIC"."SECTORS" VALUES
(1, 'Manufacturing', NULL),
(2, 'Construction materials', 1),
(3, 'Electronics and Optics', 1),
(4, 'Food and Beverage', 1),
(5, 'Bakery & confectionery products', 4),
(6, 'Beverages', 4),
(7, 'Fish & fish products', 4),
(8, 'Meat & meat products', 4),
(9, 'Milk & dairy products', 4),
(10, 'Other', 4),
(11, 'Sweets & snack food', 4),
(12, 'Furniture', 1),
(13, 'Bathroom/sauna', 12),
(14, 'Bedroom', 12),
(15, U&'Children\2019s room', 12),
(16, 'Kitchen', 12),
(17, 'Living room', 12),
(18, 'Office', 12),
(19, 'Other (Furniture)', 12),
(20, 'Outdoor', 12),
(21, 'Project furniture', 12),
(22, 'Machinery', 1),
(23, 'Machinery components', 22),
(24, 'Machinery equipment/tools', 22),
(25, 'Manufacture of machinery', 22),
(26, 'Maritime', 22),
(27, 'Aluminium and steel workboats', 26),
(28, 'Boat/Yacht building', 26),
(29, 'Ship repair and conversion', 26),
(30, 'Metal structures', 22),
(31, 'Other', 22),
(32, 'Repair and maintenance service', 22),
(33, 'Metalworking', 1),
(34, 'Construction of metal structures', 33),
(35, 'Houses and buildings', 33),
(36, 'Metal products', 33),
(37, 'Metal works', 33),
(38, 'CNC-machining', 37),
(39, 'Forgings, Fasteners', 37),
(40, 'Gas, Plasma, Laser cutting', 37),
(41, 'MIG, TIG, Aluminum welding', 37),
(42, 'Plastic and Rubber', 1),
(43, 'Packaging', 42),
(44, 'Plastic goods', 42),
(45, 'Plastic processing technology', 42),
(46, 'Blowing', 45),
(47, 'Moulding', 45),
(48, 'Plastics welding and processing', 45),
(49, 'Plastic profiles', 42),
(50, 'Printing', 1),
(51, 'Advertising', 50),
(52, 'Book/Periodicals printing', 50),
(53, 'Labelling and packaging printing', 50),
(54, 'Textile and Clothing', 1),
(55, 'Clothing', 54),
(56, 'Textile', 54),
(57, 'Wood', 1),
(58, 'Other (Wood)', 57),
(59, 'Wooden building materials', 57),
(60, 'Wooden houses', 57),
(61, 'Other', NULL),
(62, 'Creative industries', 61),
(63, 'Energy technology', 61),
(64, 'Environment', 61),
(65, 'Service', NULL),
(66, 'Business services', 65),
(67, 'Engineering', 65),
(68, 'Information Technology and Telecommunications', 65),
(69, 'Data processing, Web portals, E-marketing', 68),
(70, 'Programming, Consultancy', 68),
(71, 'Software, Hardware', 68),
(72, 'Telecommunications', 68),
(73, 'Tourism', 65),
(74, 'Translation services', 65),
(75, 'Transport and Logistics', 65),
(76, 'Air', 75),
(77, 'Rail', 75),
(78, 'Road', 75),
(79, 'Water', 75);              
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 4) NOT NULL,
    "NAME" CHARACTER VARYING(255) NOT NULL,
    "PASSWORD" CHARACTER VARYING(64) NOT NULL
);     
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'Fred', '$2a$10$lhCkuJjK.jUZYOO6IDdh7uZv4I0gzzkCcv4g0FodmPowsV53lMgiW'),
(2, 'UserWithEmptySectors', '$2a$10$ehgQgYUfmq3VSKSenbgmGOHnoIwrmjrgCOegM.rmyAbgYZ5Udjazm'),
(3, 'Linda', '$2a$10$5NPaAnbvWF/QrbPcDdzygO1GmeyRD/GeQ9F5/EwC80JzTu1YAKHAO');    
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK_3G1J96G94XPK3LPXL2QBL985X" UNIQUE("NAME");            
ALTER TABLE "PUBLIC"."SECTORS" ADD CONSTRAINT "PUBLIC"."FKQ1348EWYN6HB4VR2YYPO2OFCY" FOREIGN KEY("PARENT_ID") REFERENCES "PUBLIC"."SECTORS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."REQUESTFORM" ADD CONSTRAINT "PUBLIC"."FKDTFDE11I7B4AGMEXFU5SFR3IU" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."REQUESTFORM_SECTOR" ADD CONSTRAINT "PUBLIC"."FK2XU96KJE8YJ33QVPFOX0QD1Y2" FOREIGN KEY("SECTOR_ID") REFERENCES "PUBLIC"."SECTORS"("ID") NOCHECK;          
ALTER TABLE "PUBLIC"."REQUESTFORM_SECTOR" ADD CONSTRAINT "PUBLIC"."FKPUOM41ANTK9KJ0T70JTX5U6DA" FOREIGN KEY("REQUESTFORM_ID") REFERENCES "PUBLIC"."REQUESTFORM"("ID") NOCHECK; 
